/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d83c77e8-7cdb-4a71-8dc6-23325c1dedc3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qbAezA8oL",
    "aws_user_pools_web_client_id": "3v2lbct0h7is2lcn6k2g3kjsg2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://q4dds6zcujb2tdldusql3hlmfy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qwipumzlf5bxrpqhyunbpefnye",
    "aws_user_files_s3_bucket": "amplifyapp79a04349eb7f41959b6de63da4c9c21d232627-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
