/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d83c77e8-7cdb-4a71-8dc6-23325c1dedc3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qbAezA8oL",
    "aws_user_pools_web_client_id": "3v2lbct0h7is2lcn6k2g3kjsg2",
    "oauth": {}
};


export default awsmobile;
